name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login Docker Hub
      run: echo ${{ DOCKER_PASSWORD }} | docker login -u ${{ DOCKER_USERNAME }} --password-stdin
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag ducmeit1/kafka-client:latest --build-arg BIN=cmd/producer
    - name: Push Docker Image
      run: docker push ducmeit1/kafka-client:latest
